spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anqing
    username: root
    password: newpass
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type:  com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: LEGACYHTML5 #LEGACYHTML5
    cache: false
    prefix: classpath:/templates/ #最后需要 /
    suffix: .html
    encoding: UTF-8
    check-template-location: true
logging:
  level:
    root: debug